[project]
name = "warporacer"
version = "0.1.0"
description = "High-performance parallel reinforcement learning"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gymnasium>=1.2.3",
    "imageio[ffmpeg]>=2.37.3",
    "imgui-bundle>=1.92.700",
    "line-profiler>=5.0.2",
    "matplotlib>=3.10.9",
    "ninja>=1.11.1.2",            # Fuses compilation and smooths multi-platform TorchInductor tasks
    "numpy>=2.4.4",
    "opencv-python>=4.13.0.92",
    "pyglet>=2.1.14",
    "pyopengl>=3.1.10",
    "pyyaml>=6.0.3",
    "scikit-image>=0.26.0",
    "scipy>=1.17.1",
    "skrl>=2.0.0",
    "torch>=2.12.1",
    # Platform-specific Triton rules:
    "triton-windows>=3.7.0.post26; sys_platform == 'win32'",
    "triton; sys_platform == 'linux'",
    "typer>=0.24.1",
    "wandb>=0.26.0",
    "warp-lang>=1.13.0",
    "warp-nn>=0.1.0",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", marker = "sys_platform == 'macos'" },
  { index = "pytorch-cu132", marker = "sys_platform != 'macos'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu132"
url = "https://download.pytorch.org/whl/cu132"
explicit = true